In [2]:
# 2.2 数据预处理
import os
import pandas as pd

data_file = os.path.join("..","data","house_tiny.csv")
data = pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [4]:
inputs, outputs = data.iloc[:,0:2], data.iloc[:,2]
# inputs = inputs.fillna(inputs.mean())
inputs

NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   NaN
3       NaN   NaN

In [11]:
inputs = pd.get_dummies(inputs,dtype=float, dummy_na=True)
inputs = inputs.fillna(inputs.mean())
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True

In [14]:
# 转换为张量
import torch
x=torch.tensor(inputs.to_numpy(dtype=float))
print(x)
y=torch.tensor(outputs.to_numpy(dtype=float))
print(y)

tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=torch.float64)
tensor([127500., 106000., 178100., 140000.], dtype=torch.float64)


In [15]:
# 2.3 线性
import torch
x=torch.tensor(3.0)
y=torch.tensor(2.0)
x+y,x*y,x/y,x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [18]:
A=torch.arange(20).reshape((4,5))
A

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [19]:
A.T

tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])

In [21]:
X=torch.arange(24).reshape(2,3,4)
Y=X.clone()