In [3]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %code_wrap  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %mamba  %matplotlib  %micromamba  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%code_wrap  %%debug  %%file  %%html  %%javascript  %%js  %%latex 

In [2]:
import torch
print(torch.__version__)

2.7.1+cpu


In [8]:
%matplotlib inline
import torch
import torchvision
from torch.utils import data
from torchvision import transforms
from d2l import torch as d2l

d2l.use_svg_display()

In [11]:
# 访问元素
a1 = torch.arange(1,17).reshape((4,4))
print(a1)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])


In [12]:
# 一个元素：【1,2】
print(a1[1,2])


tensor(7)


In [13]:
# 一行 [1,:]
print(a1[1,:])

tensor([5, 6, 7, 8])


In [15]:
print(a1[:,1])

tensor([ 2,  6, 10, 14])


In [20]:
print(a1[1:3,1:3])
print(a1[1:3,1:])

tensor([[ 6,  7],
        [10, 11]])
tensor([[ 6,  7,  8],
        [10, 11, 12]])


In [25]:
print(a1[::3,::3])  # 每隔3行和3列取一个元素

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])


In [28]:
# 全0
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [29]:
# 数据预处理
import os
os.makedirs(os.path.join("..","data"), exist_ok=True)
data_file=os.path.join("..","data","house_tiny.csv")
with open(data_file, 'w') as f:
    f.write("NumRooms,Alley,Price\n")
    f.write("NA,Pave,127500\n")
    f.write("2,NA,106000\n")
    f.write("4,NA,178100\n")
    f.write("NA,NA,140000\n")

In [30]:
# 读取数据
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [44]:
# 处理缺失数据，插值，删除
inputs, outputs = data.iloc[:,:2], data.iloc[:,2]
print(inputs)
print(outputs)

# inputs = inputs.fillna(outputs.mean())
# print(inputs)

inputs = pd.get_dummies(inputs, dummy_na=True, dtype=int)
print(inputs)

inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   NaN
3       NaN   NaN
0    127500
1    106000
2    178100
3    140000
Name: Price, dtype: int64
   NumRooms  Alley_Pave  Alley_nan
0       NaN           1          0
1       2.0           0          1
2       4.0           0          1
3       NaN           0          1
   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [48]:
# inputs , outputs所有条目都是数字类型，转换成张量
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)


RuntimeError: Could not infer dtype of builtin_function_or_method